/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[38] = {34, 1, 0, 34, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[6] = {9, 1, 0, 2, 4, 5};
static const casadi_int casadi_s6[3] = {1, 0, 0};

/* unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt:(i0[5],i1[4],i2[],i3[34])->(o0,o1[9x1,2nz],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a6, a7, a8, a9;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a0*a1);
  a3=arg[3]? arg[3][4] : 0;
  a4=arg[0]? arg[0][1] : 0;
  a5=(a3*a4);
  a2=(a2+a5);
  a5=arg[3]? arg[3][2] : 0;
  a2=(a2+a5);
  a5=0.;
  a6=(a2<a5);
  a6=(!a6);
  a7=arg[3]? arg[3][18] : 0;
  a8=(a7*a2);
  a8=(a6?a8:0);
  a9=arg[3]? arg[3][3] : 0;
  a10=(a9*a1);
  a11=(a3*a4);
  a10=(a10+a11);
  a11=arg[3]? arg[3][5] : 0;
  a10=(a10+a11);
  a11=(a10<a5);
  a11=(!a11);
  a12=arg[3]? arg[3][19] : 0;
  a13=(a12*a10);
  a13=(a11?a13:0);
  a8=(a8+a13);
  a13=arg[3]? arg[3][6] : 0;
  a14=(a13*a1);
  a15=arg[3]? arg[3][7] : 0;
  a16=(a15*a4);
  a14=(a14+a16);
  a16=arg[3]? arg[3][8] : 0;
  a14=(a14+a16);
  a16=(a14<a5);
  a16=(!a16);
  a17=arg[3]? arg[3][20] : 0;
  a18=(a17*a14);
  a18=(a16?a18:0);
  a8=(a8+a18);
  a18=arg[3]? arg[3][21] : 0;
  a19=(a18*a2);
  a20=(a19*a10);
  a20=(a6?a20:0);
  a20=(a11?a20:0);
  a8=(a8+a20);
  a20=arg[3]? arg[3][22] : 0;
  a21=(a20*a2);
  a22=(a21*a10);
  a23=(a22*a14);
  a23=(a6?a23:0);
  a23=(a11?a23:0);
  a23=(a16?a23:0);
  a8=(a8+a23);
  a23=arg[3]? arg[3][12] : 0;
  a24=(a23*a1);
  a25=arg[3]? arg[3][13] : 0;
  a26=(a25*a4);
  a24=(a24+a26);
  a26=arg[3]? arg[3][14] : 0;
  a24=(a24+a26);
  a26=(a24<a5);
  a26=(!a26);
  a27=arg[3]? arg[3][9] : 0;
  a28=(a27*a1);
  a29=arg[3]? arg[3][10] : 0;
  a30=(a29*a4);
  a28=(a28+a30);
  a30=arg[3]? arg[3][11] : 0;
  a28=(a28+a30);
  a30=(a28<a5);
  a30=(!a30);
  a31=arg[3]? arg[3][23] : 0;
  a32=(a31*a2);
  a33=(a32*a28);
  a34=(a33*a24);
  a34=(a6?a34:0);
  a34=(a30?a34:0);
  a34=(a26?a34:0);
  a8=(a8+a34);
  a34=arg[3]? arg[3][24] : 0;
  a35=(a34*a10);
  a36=(a35*a28);
  a37=(a36*a24);
  a37=(a11?a37:0);
  a37=(a30?a37:0);
  a37=(a26?a37:0);
  a8=(a8+a37);
  a37=arg[3]? arg[3][15] : 0;
  a37=(a37-a1);
  a1=casadi_sq(a37);
  a38=arg[3]? arg[3][16] : 0;
  a38=(a38-a4);
  a4=casadi_sq(a38);
  a1=(a1+a4);
  a4=arg[3]? arg[3][17] : 0;
  a4=casadi_sq(a4);
  a1=(a1-a4);
  a4=(-a1);
  a4=(a4<a5);
  a4=(!a4);
  a5=arg[3]? arg[3][25] : 0;
  a39=(a5*a1);
  a40=(a39*a2);
  a41=(a40*a28);
  a41=(-a41);
  a41=(a4?a41:0);
  a41=(a6?a41:0);
  a41=(a30?a41:0);
  a8=(a8+a41);
  a41=arg[3]? arg[3][26] : 0;
  a42=(a41*a1);
  a43=(a42*a10);
  a44=(a43*a28);
  a44=(-a44);
  a44=(a4?a44:0);
  a44=(a11?a44:0);
  a44=(a30?a44:0);
  a8=(a8+a44);
  a44=arg[3]? arg[3][27] : 0;
  a45=(a44*a1);
  a46=(a45*a2);
  a46=(-a46);
  a46=(a4?a46:0);
  a46=(a6?a46:0);
  a8=(a8+a46);
  a46=arg[3]? arg[3][28] : 0;
  a47=(a46*a1);
  a48=(a47*a10);
  a48=(-a48);
  a48=(a4?a48:0);
  a48=(a11?a48:0);
  a8=(a8+a48);
  a48=arg[3]? arg[3][29] : 0;
  a49=(a48*a1);
  a50=(a49*a14);
  a50=(-a50);
  a50=(a4?a50:0);
  a50=(a16?a50:0);
  a8=(a8+a50);
  a50=arg[3]? arg[3][30] : 0;
  a51=(a50*a1);
  a52=(a51*a2);
  a53=(a52*a10);
  a53=(-a53);
  a53=(a4?a53:0);
  a53=(a6?a53:0);
  a53=(a11?a53:0);
  a8=(a8+a53);
  a53=arg[3]? arg[3][31] : 0;
  a54=(a53*a1);
  a55=(a54*a2);
  a56=(a55*a10);
  a57=(a56*a14);
  a57=(-a57);
  a57=(a4?a57:0);
  a57=(a6?a57:0);
  a57=(a11?a57:0);
  a57=(a16?a57:0);
  a8=(a8+a57);
  a57=arg[3]? arg[3][32] : 0;
  a1=(a57*a1);
  a1=(-a1);
  a1=(a4?a1:0);
  a8=(a8+a1);
  a1=arg[3]? arg[3][33] : 0;
  a8=(a8+a1);
  if (res[0]!=0) res[0][0]=a8;
  a8=(a7*a0);
  a8=(a6?a8:0);
  a1=(a12*a9);
  a1=(a11?a1:0);
  a8=(a8+a1);
  a1=(a17*a13);
  a1=(a16?a1:0);
  a8=(a8+a1);
  a1=(a18*a0);
  a1=(a10*a1);
  a58=(a19*a9);
  a1=(a1+a58);
  a1=(a6?a1:0);
  a1=(a11?a1:0);
  a8=(a8+a1);
  a1=(a20*a0);
  a1=(a10*a1);
  a58=(a21*a9);
  a1=(a1+a58);
  a1=(a14*a1);
  a58=(a22*a13);
  a1=(a1+a58);
  a1=(a6?a1:0);
  a1=(a11?a1:0);
  a1=(a16?a1:0);
  a8=(a8+a1);
  a1=(a31*a0);
  a1=(a28*a1);
  a58=(a32*a27);
  a1=(a1+a58);
  a1=(a24*a1);
  a58=(a33*a23);
  a1=(a1+a58);
  a1=(a6?a1:0);
  a1=(a30?a1:0);
  a1=(a26?a1:0);
  a8=(a8+a1);
  a1=(a34*a9);
  a1=(a28*a1);
  a58=(a35*a27);
  a1=(a1+a58);
  a1=(a24*a1);
  a23=(a36*a23);
  a1=(a1+a23);
  a1=(a11?a1:0);
  a1=(a30?a1:0);
  a1=(a26?a1:0);
  a8=(a8+a1);
  a1=(a39*a0);
  a37=(a37+a37);
  a23=(a5*a37);
  a23=(a2*a23);
  a1=(a1-a23);
  a1=(a28*a1);
  a23=(a40*a27);
  a1=(a1+a23);
  a1=(-a1);
  a1=(a4?a1:0);
  a1=(a6?a1:0);
  a1=(a30?a1:0);
  a8=(a8+a1);
  a1=(a42*a9);
  a23=(a41*a37);
  a23=(a10*a23);
  a1=(a1-a23);
  a1=(a28*a1);
  a27=(a43*a27);
  a1=(a1+a27);
  a1=(-a1);
  a1=(a4?a1:0);
  a1=(a11?a1:0);
  a1=(a30?a1:0);
  a8=(a8+a1);
  a1=(a45*a0);
  a27=(a44*a37);
  a27=(a2*a27);
  a1=(a1-a27);
  a1=(-a1);
  a1=(a4?a1:0);
  a1=(a6?a1:0);
  a8=(a8+a1);
  a1=(a47*a9);
  a27=(a46*a37);
  a27=(a10*a27);
  a1=(a1-a27);
  a1=(-a1);
  a1=(a4?a1:0);
  a1=(a11?a1:0);
  a8=(a8+a1);
  a1=(a49*a13);
  a27=(a48*a37);
  a27=(a14*a27);
  a1=(a1-a27);
  a1=(-a1);
  a1=(a4?a1:0);
  a1=(a16?a1:0);
  a8=(a8+a1);
  a1=(a51*a0);
  a27=(a50*a37);
  a27=(a2*a27);
  a1=(a1-a27);
  a1=(a10*a1);
  a27=(a52*a9);
  a1=(a1+a27);
  a1=(-a1);
  a1=(a4?a1:0);
  a1=(a6?a1:0);
  a1=(a11?a1:0);
  a8=(a8+a1);
  a0=(a54*a0);
  a1=(a53*a37);
  a1=(a2*a1);
  a0=(a0-a1);
  a0=(a10*a0);
  a9=(a55*a9);
  a0=(a0+a9);
  a0=(a14*a0);
  a13=(a56*a13);
  a0=(a0+a13);
  a0=(-a0);
  a0=(a4?a0:0);
  a0=(a6?a0:0);
  a0=(a11?a0:0);
  a0=(a16?a0:0);
  a8=(a8+a0);
  a37=(a57*a37);
  a37=(a4?a37:0);
  a8=(a8+a37);
  if (res[1]!=0) res[1][0]=a8;
  a7=(a7*a3);
  a7=(a6?a7:0);
  a12=(a12*a3);
  a12=(a11?a12:0);
  a7=(a7+a12);
  a17=(a17*a15);
  a17=(a16?a17:0);
  a7=(a7+a17);
  a18=(a18*a3);
  a18=(a10*a18);
  a19=(a19*a3);
  a18=(a18+a19);
  a18=(a6?a18:0);
  a18=(a11?a18:0);
  a7=(a7+a18);
  a20=(a20*a3);
  a20=(a10*a20);
  a21=(a21*a3);
  a20=(a20+a21);
  a20=(a14*a20);
  a22=(a22*a15);
  a20=(a20+a22);
  a20=(a6?a20:0);
  a20=(a11?a20:0);
  a20=(a16?a20:0);
  a7=(a7+a20);
  a31=(a31*a3);
  a31=(a28*a31);
  a32=(a32*a29);
  a31=(a31+a32);
  a31=(a24*a31);
  a33=(a33*a25);
  a31=(a31+a33);
  a31=(a6?a31:0);
  a31=(a30?a31:0);
  a31=(a26?a31:0);
  a7=(a7+a31);
  a34=(a34*a3);
  a34=(a28*a34);
  a35=(a35*a29);
  a34=(a34+a35);
  a24=(a24*a34);
  a36=(a36*a25);
  a24=(a24+a36);
  a24=(a11?a24:0);
  a24=(a30?a24:0);
  a26=(a26?a24:0);
  a7=(a7+a26);
  a39=(a39*a3);
  a38=(a38+a38);
  a5=(a5*a38);
  a5=(a2*a5);
  a39=(a39-a5);
  a39=(a28*a39);
  a40=(a40*a29);
  a39=(a39+a40);
  a39=(-a39);
  a39=(a4?a39:0);
  a39=(a6?a39:0);
  a39=(a30?a39:0);
  a7=(a7+a39);
  a42=(a42*a3);
  a41=(a41*a38);
  a41=(a10*a41);
  a42=(a42-a41);
  a28=(a28*a42);
  a43=(a43*a29);
  a28=(a28+a43);
  a28=(-a28);
  a28=(a4?a28:0);
  a28=(a11?a28:0);
  a30=(a30?a28:0);
  a7=(a7+a30);
  a45=(a45*a3);
  a44=(a44*a38);
  a44=(a2*a44);
  a45=(a45-a44);
  a45=(-a45);
  a45=(a4?a45:0);
  a45=(a6?a45:0);
  a7=(a7+a45);
  a47=(a47*a3);
  a46=(a46*a38);
  a46=(a10*a46);
  a47=(a47-a46);
  a47=(-a47);
  a47=(a4?a47:0);
  a47=(a11?a47:0);
  a7=(a7+a47);
  a49=(a49*a15);
  a48=(a48*a38);
  a48=(a14*a48);
  a49=(a49-a48);
  a49=(-a49);
  a49=(a4?a49:0);
  a49=(a16?a49:0);
  a7=(a7+a49);
  a51=(a51*a3);
  a50=(a50*a38);
  a50=(a2*a50);
  a51=(a51-a50);
  a51=(a10*a51);
  a52=(a52*a3);
  a51=(a51+a52);
  a51=(-a51);
  a51=(a4?a51:0);
  a51=(a6?a51:0);
  a51=(a11?a51:0);
  a7=(a7+a51);
  a54=(a54*a3);
  a53=(a53*a38);
  a2=(a2*a53);
  a54=(a54-a2);
  a10=(a10*a54);
  a55=(a55*a3);
  a10=(a10+a55);
  a14=(a14*a10);
  a56=(a56*a15);
  a14=(a14+a56);
  a14=(-a14);
  a14=(a4?a14:0);
  a6=(a6?a14:0);
  a11=(a11?a6:0);
  a16=(a16?a11:0);
  a7=(a7+a16);
  a57=(a57*a38);
  a4=(a4?a57:0);
  a7=(a7+a4);
  if (res[1]!=0) res[1][1]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unicycle_keyhole_mpc_constr_h_0_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
